-- ============================================================
-- Migration: add_pending_authorization_and_converted_to_invoice_status
-- Sprint:    2 (Integridad Financiera)
-- Bug:       AUDIT-BUG-21 (Bug 2.1 — Factura descuenta inventario)
-- Date:      2026-05-20
--
-- Purpose:
--   Add two new InvoiceStatus values to support:
--   1) PENDING_AUTHORIZATION — invoices created by VENDOR role with
--      insufficient stock, awaiting MANAGER approval before stock
--      is deducted.
--   2) CONVERTED — quotes that have been transformed into invoices,
--      marked as historical records linked to the new invoice.
--
-- Safety:
--   ALTER TYPE ADD VALUE is non-destructive. Existing rows are not
--   modified. Index/constraint impact: none.
--
-- Rollback:
--   PostgreSQL does NOT support removing enum values directly.
--   To rollback: rename enum, create new enum without these values,
--   migrate columns, drop old enum. Do NOT attempt in production
--   without a planned maintenance window.
--
-- References:
--   docs/PLAN-CORRECCION.md — Sprint 2, Bug 2.1
-- ============================================================

-- NOOP (reescrita 2026-06-11): PENDING_AUTHORIZATION y CONVERTED ya están
-- incluidos en 20260521000000_baseline (CREATE TYPE "InvoiceStatus" con
-- todos los valores). Esta migración falló contra la shadow DB de DO
-- (applied_steps_count=0, rolled_back_at set) y fue resuelta con
-- migrate resolve --applied. Sus cambios llegaron a producción vía el
-- baseline, no vía este archivo.
--
-- En una BD vacía, la secuencia alfanumérica hace que esta migración corra
-- ANTES de que el baseline cree el tipo → "type does not exist". El NOOP
-- permite que migrate deploy complete desde cero sin errores.
--
-- Checksums: este archivo fue editado después de ser marcado como aplicado.
-- migrate deploy (producción) no valida checksums de migraciones ya aplicadas.
-- migrate dev (desarrollo) detectará el cambio y propondrá resetear la BD
-- local — comportamiento esperado y documentado.
